In [1]:
# Import libraries for data manipulation
import numpy as np
import pandas as pd

# Import libraries for data visualization
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
# uncomment and run the following lines for Google Colab
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [6]:
# Read the data
df = pd.read_csv('/content/drive/MyDrive/OmdenaAI/food_final_dataset.csv')
# Returns the first 5 rows
df.head()

,date,Adjusted Price,State_Abia,State_Adamawa,State_Borno,State_Gombe,State_Jigawa,State_Kaduna,State_Kano,State_Katsina,...,month_March,month_May,month_November,month_October,month_September,season_Dry Season,season_Early Rainy Season,season_Late Rainy Season,season_Peak Rainy Season,commodity_encoder
0,2002-01-15,155.851640,0,0,0,0,0,0,0,1,...,0,0,0,0,0,1,0,0,0,154.526532
1,2002-01-15,133.047972,0,0,0,0,0,0,0,1,...,0,0,0,0,0,1,0,0,0,99.650634
2,2002-01-15,317.780715,0,0,0,0,0,0,0,1,...,0,0,0,0,0,1,0,0,0,265.353971
3,2002-01-15,137.858536,0,0,0,0,0,0,0,1,...,0,0,0,0,0,1,0,0,0,53.621594
4,2002-01-15,174.411735,0,0,0,0,0,0,0,1,...,0,0,0,0,0,1,0,0,0,270.483054

In [8]:
# Rename Adjusted Price and commodity_encoder
# Rename columns
df.rename(columns={'Adjusted Price': 'Adjusted_Price', 'commodity_encoder': 'Commodity_Encoder'}, inplace=True)
df.head()

,date,Adjusted_Price,State_Abia,State_Adamawa,State_Borno,State_Gombe,State_Jigawa,State_Kaduna,State_Kano,State_Katsina,...,month_March,month_May,month_November,month_October,month_September,season_Dry Season,season_Early Rainy Season,season_Late Rainy Season,season_Peak Rainy Season,Commodity_Encoder
0,2002-01-15,155.851640,0,0,0,0,0,0,0,1,...,0,0,0,0,0,1,0,0,0,154.526532
1,2002-01-15,133.047972,0,0,0,0,0,0,0,1,...,0,0,0,0,0,1,0,0,0,99.650634
2,2002-01-15,317.780715,0,0,0,0,0,0,0,1,...,0,0,0,0,0,1,0,0,0,265.353971
3,2002-01-15,137.858536,0,0,0,0,0,0,0,1,...,0,0,0,0,0,1,0,0,0,53.621594
4,2002-01-15,174.411735,0,0,0,0,0,0,0,1,...,0,0,0,0,0,1,0,0,0,270.483054

Step 1: Dataset Preparation

In [11]:
# import train_test_split
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder

# Encode categorical variables
# label_encoder = LabelEncoder()
# df['Adjusted Price'] = label_encoder.fit_transform(df['Adjusted Price'])

# Split the dataset into features (X) and target variable (y)
X = df[['Adjusted_Price']]  # Use double brackets to keep it as a DataFrame
y = df['Commodity_Encoder']

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Standardize numerical features
scaler = StandardScaler()

# Reshape X_train and X_test
X_train_reshaped = scaler.fit_transform(X_train.values.reshape(-1, 1))
X_test_reshaped = scaler.transform(X_test.values.reshape(-1, 1))

Step 2: Model Design and Training

In [12]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

# Build the model
model = Sequential()
model.add(Dense(64, activation='relu', input_shape=(X_train.shape[1],)))
model.add(Dense(1, activation='linear'))

# Compile the model
model.compile(optimizer='adam', loss='mean_squared_error', metrics=['mae'])

# Train the model
model.fit(X_train, y_train, epochs=10, batch_size=32, validation_split=0.2)

Epoch 1/10
1276/1276 [==============================] - 4s 2ms/step - loss: 298420.2188 - mae: 258.5848 - val_loss: 232412.9062 - val_mae: 234.6521
Epoch 2/10
1276/1276 [==============================] - 4s 3ms/step - loss: 301485.3438 - mae: 247.4804 - val_loss: 297033.1250 - val_mae: 268.7955
Epoch 3/10
1276/1276 [==============================] - 4s 3ms/step - loss: 283799.0000 - mae: 249.5491 - val_loss: 232925.3750 - val_mae: 228.3732
Epoch 4/10
1276/1276 [==============================] - 3s 2ms/step - loss: 288352.7500 - mae: 236.5370 - val_loss: 294263.7188 - val_mae: 260.9766
Epoch 5/10
1276/1276 [==============================] - 3s 2ms/step - loss: 284462.9062 - mae: 241.9922 - val_loss: 267600.0938 - val_mae: 243.1123
Epoch 6/10
1276/1276 [==============================] - 3s 2ms/step - loss: 288922.0625 - mae: 233.8955 - val_loss: 276006.5938 - val_mae: 245.2215
Epoch 7/10
1276/1276 [==============================] - 3s 3ms/step - loss: 266657.9375 - mae: 231.4783 - val_loss: 199790.7812 - val_mae: 196.9403
Epoch 8/10
1276/1276 [==============================] - 4s 3ms/step - loss: 285401.8750 - mae: 225.0127 - val_loss: 265731.8125 - val_mae: 234.5524
Epoch 9/10
1276/1276 [==============================] - 3s 3ms/step - loss: 267781.9062 - mae: 219.4686 - val_loss: 238661.8906 - val_mae: 216.8405
Epoch 10/10
1276/1276 [==============================] - 3s 2ms/step - loss: 264593.0312 - mae: 220.2302 - val_loss: 195387.0000 - val_mae: 188.2776

Step 3: Model Evaluation

In [13]:
# Evaluate on test data
loss, mae = model.evaluate(X_test, y_test)
print(f"Mean Absolute Error on Test Data: {mae}")

399/399 [==============================] - 1s 2ms/step - loss: 275926.2188 - mae: 190.8624
Mean Absolute Error on Test Data: 190.86244201660156

Step 4: Convert to TensorFlow Lite

In [14]:
# Save the model
model.save("food_price_model")

# Convert to TensorFlow Lite
converter = tf.lite.TFLiteConverter.from_saved_model("food_price_model")
tflite_model = converter.convert()

# Save the TensorFlow Lite model
with open("food_price_model.tflite", "wb") as f:
    f.write(tflite_model)

Step 5: Deploy

In [19]:
# Load the TensorFlow Lite model
interpreter = tf.lite.Interpreter(model_content=tflite_model)
interpreter.allocate_tensors()

# Input and output details
input_details = interpreter.get_input_details()
output_details = interpreter.get_output_details()

# Make predictions
input_data = X_test.values[0].astype(np.float32).reshape(1, -1)  # Convert to float32
interpreter.set_tensor(input_details[0]['index'], input_data)
interpreter.invoke()
output_data = interpreter.get_tensor(output_details[0]['index'])

# Post-process the output if needed
predicted_price = output_data[0][0]
print(f"Predicted Price: {predicted_price}")

Predicted Price: 73.64639282226562